### ISSUE TITLE
Is this supposed to enable a console?

### ISSUE THREAD

**Issue by rlewkowicz** [UE4SS/UE4SS#1]
Apologies for the ignorance in advance. This might be more a tool for people that already know what they're doing. I'm starting to explore this space of UE4 manipulation and this was listed as a tool that can unlock a console in UE4 games. The directions make it seem plug and play, but it doesn't seem to do anything... I'm trying to mess with back4blood and have some successes, but in order to do what I'm trying too, I need to get deeper into this space that makes these objects more verbose. 

I can mess with and understand AOB's, but what would indicate I even need to do that?

**Comment by rlewkowicz** [comment]
I got it, I was running an EAC bypass andI think that made issues for me, bt it also turns out that I had to set the info in the ini and now I do have to go set those aobs.

**Comment by UE4SS** [comment]
Sorry for the long delay.
I haven't been getting any notifications from this repo, so I wasn't aware that any issues had been created.

I've reworked some of the AOBs for 1.2 so if you're still having that particular issue, you could try 1.2 PreRelease 1.

**Comment by rlewkowicz** [comment]
Chances are b4b removes those AOB's intentionally. I've not had a chance to circle back to this, as I've taken some other routes. Closing for now.
