### ISSUE TITLE
Crashes on injection

### ISSUE THREAD

**Issue by JillCrungus** [UE4SS/UE4SS#5]
I've not been able to have any success injecting UE4SS into any game with any method and it always outright crashes without any useful error, the log only contains a timestamped "Console created".

Does UE4SS depend on anything that isn't available in Windows 7? Since I use Windows 7 I'm wondering if this might be the problem.

**Comment by UE4SS** [comment]
Contact me on discord and I can help you with this problem.
CheatingMuppet#3301.

**Comment by UE4SS** [comment]
This was an incompatibility with Windows 7 which has now been fixed and will be included in the next release.

**Comment by plushbean** [comment]
i have the exact same issue using 1.3.5 xinput on win7
