### ISSUE TITLE
Need a small help

### ISSUE THREAD

**Issue by DeadMor0z** [UE4SS/UE4SS#6]
Hello!
Please, can you help me with these (lua mod):
1. There is static function I want to use - "Function /Script/Maine.SurvivalGameplayStatics:GetLocalSurvivalPlayerCharacter" (from objectdump). I should call `local func = StaticFindOblect("/Script/Maine.SurvivalGameplayStatics:GetLocalSurvivalPlayerCharacter")`, right? And then use `func()`?
3. Many of functions require WorldContextObject - how can I get it? I havent found any function which returns it.

**Comment by DeadMor0z** [comment]
I've figured it out:
first, find default class with statics functions:
`local statics = StaticFindOblect("/Script/Maine.SurvivalGameplayStatics")`
then find worldcontext:
'local engine = FindFirstOf("Engine")
local context = engine.GameViewport`
finally, call static function:
`local player = statics:GetLocalSurvivalPlayerCharacter(context)`

Now next question:
there is an object wich has a Fstring property `CustomName` and a function ` void SetCustomName(const FString& NewName)`
how do I call this function properly? If I call `instance:SetCustomName("123")` then there is an error `[Lua::call_function] lua_pcall returned [push_strproperty] Operation::Set is not supported
stack traceback:
        [C]: in method 'SetCustomName'`

**Comment by UE4SS** [comment]
> I've figured it out: first, find default class with statics functions: `local statics = StaticFindOblect("/Script/Maine.Default__SurvivalGameplayStatics")` then find worldcontext:
> 
> ```
> local engine = FindFirstOf("Engine")
> local context = engine.GameViewport
> ```
> 
> finally, call static function: `local player = statics:GetLocalSurvivalPlayerCharacter(context)`
> 
> Now next question: there is an object wich has a FString property `CustomName` and a function ` void SetCustomName(const FString& NewName)` how do I call this function properly? If I call `instance:SetCustomName("123")` then there is an error
> 
> ```
> [Lua::call_function] lua_pcall returned [push_strproperty] Operation::Set is not supported
> stack traceback:
>         [C]: in method 'SetCustomName'
> ```

Your syntax is correct, however, setting the value of a StrProperty/FString is not supported at the moment but this is due to my own laziness and lack of need.
I should be able to add support for this fairly easily and I recommend that you add me on discord because that way I can get you a version of UE4SS with this feature asap.

My discord is: CheatingMuppet#3301
